### PR TITLE
Expose AsyncMap keys, values and entries

### PR DESCRIPTION
**Pull request by tsegismont**
See https://github.com/eclipse/vert.x/issues/2020

### CODE REVIEW

**Comment by tsegismont** [comment]
@agura can you please review? But please do not merge yet since @vietj must approve the PR in core first. Thanks

**Comment by agura** [comment]
@tsegismont I've looked at changes. Looks good for me. Wait for related changes in core.
Thanks!

**Comment by agura** [comment]
Thanks a lot!

**Comment by tsegismont** [comment]
You're welcome :-)

2017-09-21 18:28 GMT+02:00 Andrey Gura <notifications@github.com>:

**Pull request merged**
