### PR TITLE
Updated SubsMapHelper and IgniteClusterManager to solve subscriber cl…

### PR DESCRIPTION
**Pull request by edtbl76**
…eanup and duplicate subscriber issues

Motivation:

Explain here the context, and why you're making that change, what is the problem you're trying to solve.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by edtbl76** [comment]
This is an intermittent test failure: 
(we experienced it trying to run the tests w/ or w/o the changes) 

It's from vertx-core: (AsyncTestBase)

        // timed out
        throw new IllegalStateException("Timed out in waiting for test complete");

**Comment by tsegismont** [comment]
@agura @zyclonite can you please review?

**Comment by zyclonite** [comment]
lgtm

**Comment by edtbl76** [comment]
I get that test failure locally now and then as well. I'll try to take a look and see if there is something we can do to make it more consistent. (We have some pushes to make against vertx-core, so we'll have the patient open for surgery)

**Comment by zyclonite** [comment]
i could not reproduce it locally but maybe test against other cluster managers

**Comment by edtbl76** [comment]
Its pretty infrequent locally. I can't get it to fail today.

**Comment by edtbl76** [comment]
Is there anything I need to do to have this pulled in? The build failure is a vertx-core issue (Test timeout).

**Comment by zyclonite** [comment]
@edtbl76 could you please rebase so this pr could be merged

**Comment by zyclonite** [comment]
@tsegismont can be closed, is already included in #96

**Pull request closed without merging**
