### PR TITLE
Implement replace and replaceIfPresent with TTL

### PR DESCRIPTION
**Pull request by zyclonite**
Motivation:

Implement the new methods from https://github.com/eclipse-vertx/vert.x/pull/3744 for Ignite

### CODE REVIEW

**Review by tsegismont — APPROVED** [review]

**Comment by tsegismont** [comment]
LGTM, thanks @zyclonite

Waiting for the Vert.x core PR to be merged and test suite passing before merging.

**Comment by tsegismont** [comment]
@zyclonite can you please rebase?

**Comment by zyclonite** [comment]
@tsegismont on it

**Comment by tsegismont** [comment]
CI is green, please go ahead and merge

**Pull request merged**
