### PR TITLE
Fault tolerance for event bus subscription

### PR DESCRIPTION
**Pull request by tsegismont**
See eclipse/vert.x#1848

I couldn't make the FaultToleranceTest work but it seems to be a
configuration problem.

I tried the original reproducer (see vert-x3/vertx-hazelcast#13) with
this cluster manager and the issue is fixed.

### CODE REVIEW

**Comment by tsegismont** [comment]
@agura can you have a look please? Thanks

**Comment by tsegismont** [comment]
@agura The upstream PR has been merged, so I'll go ahead and merge this one. If there's any issue we'll revert it.

**Comment by agura** [comment]
@tsegismont There are no any issues. Thank you very much!

**Comment by tsegismont** [comment]
Thanks for the feedback!

2017-03-06 15:39 GMT+01:00 Andrey Gura <notifications@github.com>:

**Pull request merged**
