### PR TITLE
ClusterSerializable support added

### LINKED ISSUE #60: Failed to store session with IgniteClusterManager but succeed with HazelcastClusterManager
Moved from vert-x3/vertx-web#793

### Version

* vert.x core: 3.5.0
* vert.x web: 3.5.0

### Context
hello, when i use IgniteClusterManager , Failed to store session ，but change HazelcastClusterManager,it works right。

with IgniteClusterManager  ,excption message is: 
javax.cache.CacheException: class org.apache.ignite.IgniteCheckedException: Failed to serialize object: {87851d06-3e06-4418-9131-f884123adbf6=io.vertx.core.impl.DeploymentManager$DeploymentImpl@660d9876, 419334ef-cfd6-4a1e-8711-184a8da391b7=io.vertx.core.impl.DeploymentManager$DeploymentImpl@530374f2, 379c09e8-7524-41d4-8800-6c9aeaf50d38=io.vertx.core.impl.DeploymentManager$DeploymentImpl@629b4cf5}

here is my code ：
```
       IgniteClusterManager clusterManager = new IgniteClusterManager();
//        HazelcastClusterManager clusterManager = new HazelcastClusterManager();
        VertxOptions vertxOptions = new VertxOptions().setClusterManager(clusterManager);
        Future<Vertx> vertxFuture = Future.future();

      router.route().handler(CookieHandler.create());
        // create default clustered session
        SessionStore store = ClusteredSessionStore.create(this.vertx);
        SessionHandler sessionHandler = SessionHandler.create(store);
        router.route().handler(sessionHandler);

        Session session = routingContext.session();
        session.put("user", new JsonObject().put("a","a"));
```

### PR DESCRIPTION
**Pull request by agura**
Closes #60

### CODE REVIEW

**Comment by tsegismont** [comment]
@agura can update `IgniteClusteredAsyncMapTest` so that the `ClusterSerializable` tests get executed? I just tried, they pass. Also, I tried the session clustering test, it passes in this branch, great!

Now I will take a closer look at the code.

**Comment by agura** [comment]
@tsegismont Updated. Tested. Ok.

**Comment by tsegismont** [comment]
@agura merged, thanks! I added `IgniteClusteredSessionHandlerTest` while merging

**Comment by tsegismont** [comment]
@agura can you please add a note in https://github.com/vert-x3/wiki/wiki/3.5.1-Breaking-Changes ? Users should be warned that cache keys and values are now wrapped if the object is `ClusterSerializable`

**Comment by agura** [comment]
@tsegismont Good point! I'll do.

**Comment by agura** [comment]
Note about breaking change added to the Wiki.

**Pull request merged**
