### PR TITLE
Ensure message order is preserved

### PR DESCRIPTION
**Pull request by tsegismont**
On the CI server, the #sendNoContext test fails intermittently because this CM does not ensure message order is preserved (per context).

### CODE REVIEW

**Comment by tsegismont** [comment]
Please review but do not merge before release 3.4.1 is out

**Comment by agura** [comment]
@tsegismont I'll take a look today. Thanks!

**Comment by agura** [comment]
@tsegismont Looks good for me. Why we are waiting for release 3.4.1 instead of merge something in vertx-core?

**Comment by tsegismont** [comment]
Because there's a general code freeze until 3.4.1 is out. Should be soon.

2017-03-14 0:27 GMT+01:00 Andrey Gura <notifications@github.com>:

**Pull request merged**
