### PR TITLE
Test locking on same Vert.x instance

### PR DESCRIPTION
**Pull request by tsegismont**
See eclipse/vert.x#1732

### CODE REVIEW

**Comment by agura** [comment]
@tsegismont Looks good. Thanks a lot!

**Comment by tsegismont** [comment]
Can you revert the merge and reopen this PR? The upstream core change has not been merged yet.

**Comment by agura** [comment]
@tsegismont Do you mean this PR https://github.com/eclipse/vert.x/pull/1732 ?
It contains only tests. I think this change is safe. Am I wrong?

**Comment by tsegismont** [comment]
Yes, right, sorry for the confusion.

2016-12-24 16:29 GMT+01:00 Andrey Gura <notifications@github.com>:

**Pull request merged**
