### PR TITLE
upgrade clustering spi and ignite to 2.8.0

### PR DESCRIPTION
**Pull request by zyclonite**
Motivation:

Does not work with latest jdk versions (tested with 14)
Could block thread in some cases when doing a distributed lock (randomly happened during unit tests)

Changes:

* clustering spi update
* upgrade ignite to 2.8.0
* fix eventloop blocking when acquire lock was retried
* refactor lock implementation to use semaphore
* fix putAll in MapImpl
* remove not needed ignite-index (lucene) maven dependency
* split __vertx.* and default map template in configuration

### CODE REVIEW

**Comment by vietj** [comment]
@agura can you review this PR ?

**Comment by zyclonite** [comment]
@vietj based on the activity in this repo, do you expect a chance to get this reviewed before 4.x is released?
if that cluster manager get's to a quality level comparable to the hazelcast one, it could be a good replacement if someone needs an opensource option for tls enabled cluster node communication

**Comment by vietj** [comment]
@zyclonite there is an upcoming changes in clustering SPI conducted by @tsegismont in vertx-core by this PR : https://github.com/eclipse-vertx/vert.x/pull/3132 . @tsegismont has done the Hazelcast and Infinispan implementation

we will need somebody to do this for Ignite as well, is that something you can contribute ?

**Comment by zyclonite** [comment]
sure, i will try my best

**Comment by vietj** [comment]
that would be great, you can look at @tsegismont at this PR to have an example with HZ https://github.com/vert-x3/vertx-hazelcast/pull/126

**Comment by zyclonite** [comment]
@tsegismont please have a look

**Comment by zyclonite** [comment]
@tsegismont thank you for the feedback
version update will fix #80 
i created an issue for the lock change #83 

i changed the copyright header to the correct version and i hope i understood you correctly on the javadoc part

i added the missing discovery test (RegistrationLister was already in the prev commit)

**Comment by tsegismont** [comment]
Thank you @zyclonite . I am going to test the branch locally.

**Comment by tsegismont** [comment]
@zyclonite the build fails quickly on my box.

I see a lot of

```
java.lang.NullPointerException: null
	at io.vertx.servicediscovery.impl.DiscoveryImplTestBase.tearDown(DiscoveryImplTestBase.java:61)
```

**Comment by zyclonite** [comment]
@tsegismont everything else i could test properly, but i could not even get the hz discovery test up and running (did i miss something, i only use your vert.x spi branch at the moment, do i need to use any other discovery ext version?)

**Comment by tsegismont** [comment]
@zyclonite ah right, this is because the service discovery test has not been adapted to the new SPI yet. The other tests seem to run fine.

We are finalizing the SPI changes right now, as soon they are merged in master I will come back to you.

Subscribe to https://github.com/eclipse-vertx/vert.x/pull/3132 if you're interested.

**Comment by zyclonite** [comment]
@tsegismont seems that this tests fails for this project as well as for the hazelcast one
* `ClusteredEventbusTest.testImmediateUnregistration` with `Consumer unregistered before registration completed` 
* `ClusteredEventbusTest.testLocalHandlerClusteredPublish` with a timeout

any idea what to look for?

all the rest looks good after rebasing

**Comment by tsegismont** [comment]
@zyclonite `ClusteredEventbusTest.testImmediateUnregistration` has been updated in Vert.x core. I am looking into `testLocalHandlerClusteredPublish`.

Thanks for updating the PR

**Comment by zyclonite** [comment]
@tsegismont i followed your changes in the core project, rerun tests on friday and they were all green

**Comment by tsegismont** [comment]
@zyclonite thank you very much !

**Pull request merged**
