### PR TITLE
add dependabot configuration 

### PR DESCRIPTION
**Pull request by yeikel**
See https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### CODE REVIEW

**Comment by zyclonite** [comment]
dependabot is enabled in the settings of this repository, currently there is no custom override needed

**Comment by yeikel** [comment]
What are the options that you have configured in the repo? The alerts? Or the actual pull requests? 

Because as far as I can see, I do not see any automated PR in this repo from Dependabot (the original goal of this pull request)

**Comment by zyclonite** [comment]
see this one: https://github.com/vert-x3/vertx-ignite/pull/115

for the underlying cluster framework upgrades there is anyway a lot of manual activities needed, so it does not really add a lot of value

**Comment by yeikel** [comment]
> see this one: #115
> 
> for the underlying cluster framework upgrades there is anyway a lot of manual activities needed, so it does not really add a lot of value

Thank you for clarifying. 

What schedule do you  currently have? 

I understand that major upgrades usually need manual intervention (receiving pull requests with draft upgrades is still valuable IMHO), but for other minor upgrades like [logback ](https://github.com/vert-x3/vertx-ignite/commit/59e60301a2982891247c0344114476b072465e11#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L107) I think that it can some value

**Comment by zyclonite** [comment]
there is not really many dependencies... logback is only for testing and the majority for the stack gets handled by the `vertx-dependencies` project

**Pull request closed without merging**
